const {chromium}=await import(process.env.ACADEMY_PLAYWRIGHT_MODULE||'playwright-core');
import fs from 'node:fs/promises';import {resolve} from 'node:path';import {createHmac,randomBytes} from 'node:crypto';import assert from 'node:assert/strict';
const secret=randomBytes(32).toString('hex');const env={ACADEMY_SESSION_SECRET:secret,ASSETS:{fetch:async r=>{try{return new Response(await fs.readFile('public'+new URL(r.url).pathname));}catch{return new Response('Not found',{status:404});}}}};globalThis.__academyTestEnv=env;
const {default:worker}=await import('../dist/server/index.js');const contextArgs={waitUntil(){},passThroughOnException(){}};
const browser=await chromium.launch({executablePath:process.env.ACADEMY_CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const results=[],failures=[],pageErrors=[];await fs.mkdir('work/learning-browser',{recursive:true});
const mime=path=>path.endsWith('.wasm')?'application/wasm':path.endsWith('.css')?'text/css':path.endsWith('.svg')?'image/svg+xml':path.endsWith('.json')?'application/json':path.endsWith('.zip')?'application/zip':'application/javascript';
try{
 for(const role of ['student','teacher']){
 const context=await browser.newContext();const payload=`${role}.${Math.floor(Date.now()/1000)+3600}`;const cookie=payload+'.'+createHmac('sha256',secret).update(payload).digest('hex');await context.addCookies([{name:'academy_access',value:cookie,domain:'academy.test',path:'/',secure:true,httpOnly:true}]);
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.hostname!=='academy.test')return route.abort();if(url.pathname.startsWith('/assets/')||url.pathname.startsWith('/python-runtime/')||url.pathname==='/python-lab-worker.mjs'||url.pathname==='/favicon.svg'){try{return route.fulfill({body:await fs.readFile('dist/client'+url.pathname),contentType:mime(url.pathname)});}catch{return route.abort();}}const response=await worker.fetch(new Request(req.url(),{method:req.method(),headers:{...req.headers(),cookie:`academy_access=${cookie}`}}),env,contextArgs);return route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
 const page=await context.newPage();page.on('pageerror',e=>pageErrors.push({path:page.url(),error:String(e)}));
 const paths=[`/learn/${role}`,`/learn/${role}/python-bridge`,`/learn/${role}/ai-1/1?resource=lesson`,`/learn/${role}/ai-1/1?resource=workbook`,`/learn/${role}/ai-5/15?resource=lesson`,...(role==='teacher'?[`/learn/teacher/ai-1/1?resource=guide`,`/learn/teacher/pilot`]:[])];
 for(const width of [1280,390])for(const path of paths){await page.setViewportSize({width,height:900});await page.goto('https://academy.test'+path,{waitUntil:'networkidle'});await page.addScriptTag({path:resolve(process.env.ACADEMY_AXE_PATH||'work/learning-audit/node_modules/axe-core/axe.min.js')});const audit=await page.evaluate(async()=>await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}}));const violations=audit.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));results.push({role,path,width,violations});if(violations.length)failures.push({path,width,violations});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),path);}
 await page.goto(`https://academy.test/learn/${role}/ai-1/1?resource=workbook`,{waitUntil:'networkidle'});await page.locator('textarea').first().fill('I compared a written rule with a learned decision.');await page.locator('.portfolio-tools summary').click();await page.locator('.portfolio-tools textarea').first().fill('My project test used a changed input.');let event=page.waitForEvent('download');await page.getByRole('button',{name:'Download completed work (.html)'}).click();const download=await event;const exported=await fs.readFile(await download.path(),'utf8');assert.ok(exported.includes('I compared a written rule'));assert.ok(exported.includes('My project test used a changed input.'));assert.ok(!exported.includes('<script>'));
 await page.goto(`https://academy.test/learn/${role}/ai-1/1?resource=lesson`,{waitUntil:'networkidle'});const data=JSON.parse(await fs.readFile('lib/learning-tools.json','utf8'))['ai-1/1'];const falseChoice=data.questions[0].choices.findIndex(c=>!c.correct);await page.locator('.formative-practice input').nth(falseChoice).check();await page.getByRole('button',{name:'Check my reasoning'}).click();assert.ok(await page.getByText('Revisit the deciding step.',{exact:false}).isVisible());await page.getByRole('button',{name:'Give me a hint'}).click();await page.locator('.formative-practice input').nth(data.questions[0].choices.findIndex(c=>c.correct)).check();await page.getByRole('button',{name:'Check my reasoning'}).click();await page.getByRole('button',{name:'Try the changed case'}).click();assert.ok(await page.locator('.formative-practice').getByText('Changed-case practice:',{exact:false}).isVisible());
 await page.goto(`https://academy.test/learn/${role}/python-bridge/1?resource=lesson`,{waitUntil:'networkidle'});await page.locator('.python-lab .python-editor').fill('print(7 * 3)');await page.getByRole('button',{name:'Run Python',exact:true}).click();await page.locator('.actual-python-output').waitFor({timeout:60000});assert.equal(await page.locator('.actual-python-output').textContent(),'21');await page.locator('.python-lab .python-editor').fill('while True:\n    pass');await page.getByRole('button',{name:'Run Python',exact:true}).click();await page.getByText('Stopped after five seconds.',{exact:false}).waitFor({timeout:15000});
 await page.locator('.python-lab .python-editor').fill('print(8)');await page.getByRole('button',{name:'Run Python',exact:true}).click();await page.locator('.actual-python-output').waitFor({timeout:60000});assert.equal(await page.locator('.actual-python-output').textContent(),'8');
 await page.goto(`https://academy.test/learn/${role}/ai-2/10?resource=lesson`,{waitUntil:'networkidle'});assert.ok(await page.locator('.prerequisite-repair details').count()>0);await page.locator('.prerequisite-repair summary').first().click();await page.locator('.prerequisite-repair a').first().click();await page.waitForURL(/\/learn\/(student|teacher)\/ai-2\/\d+#section-/);
 await page.goto(`https://academy.test/learn/${role}`,{waitUntil:'networkidle'});await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Skip to learning content');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement?.id),'main-content');await page.setViewportSize({width:640,height:450});await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`work/learning-browser/zoom-${role}.png`,fullPage:true});
 if(role==='teacher'){await page.goto('https://academy.test/learn/teacher/pilot',{waitUntil:'networkidle'});assert.ok(await page.getByText('0 records · 0 learner codes',{exact:false}).isVisible());const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download selected learner task (.html)'}).click();const handout=await fs.readFile(await (await pending).path(),'utf8');assert.ok(!handout.includes('Teacher reasoning key'));assert.ok(!handout.includes('<h2>delayed task'));assert.ok(handout.includes('<h2>baseline task'));}
 await context.close();console.log(role,'portfolio, feedback, actual Python/timeout/recovery, repairs, keyboard and zoom passed.');
 }
 await fs.writeFile('reports/learning-accessibility-validation.json',JSON.stringify({pages:results.length,failures,pageErrors,results},null,2));assert.deepEqual(pageErrors,[]);assert.deepEqual(failures,[]);console.log(results.length,'accessibility page audits passed.');
}finally{await browser.close();}
