"use client";
import {useEffect,useId,useState} from "react";
import type {PracticeQuestion,Repair} from "@/lib/learning/tools";
import {ResponseSpace} from "@/components/response-space";
export function FormativePractice({week,role,scenario,questions,repairs}:{week:string;role:string;scenario:string;questions:PracticeQuestion[];repairs:Repair[]}){
 const id=useId();const[index,setIndex]=useState(0);const[selected,setSelected]=useState<number|null>(null);const[checked,setChecked]=useState(false);const[attempts,setAttempts]=useState(0);const[hint,setHint]=useState(false);const[helpUsed,setHelpUsed]=useState(false);
 useEffect(()=>{setIndex(0);setSelected(null);setChecked(false);setAttempts(0);setHint(false);setHelpUsed(false);},[week,role]);
 const q=questions[index],choice=selected===null?null:q.choices[selected];
 function check(){if(selected===null)return;setChecked(true);setAttempts(attempts+1);const key=`academy-answer-v1:/learn/${role}/${week}:practice:${q.id}`;try{localStorage.setItem(key,`Question: ${q.prompt}\nMy choice: ${choice?.text}\nFeedback: ${choice?.feedback}\nAttempts: ${attempts+1}; hint used: ${helpUsed?'yes':'no'}. Formative practice, not independent mastery.`);localStorage.setItem(`academy-answer-meta-v1:${key}`,JSON.stringify({prompt:q.prompt,updatedAt:new Date().toISOString()}));}catch{}}
 return <section className="classroom-panel formative-practice"><h2>Practise with feedback</h2><p>{scenario}</p><p>Use this supported practice to check your reasoning. Your independent assessment stays separate.</p><fieldset><legend>{q.prompt}</legend>{q.choices.map((option,i)=><label key={i}><input type="radio" name={`${id}-${index}`} checked={selected===i} onChange={()=>{setSelected(i);setChecked(false);}}/>{option.text}</label>)}</fieldset><div className="learning-actions"><button type="button" disabled={selected===null} onClick={check}>Check my reasoning</button><button type="button" aria-expanded={hint} onClick={()=>{setHint(!hint);setHelpUsed(true);}}>{hint?'Hide hint':'Give me a hint'}</button></div>{hint&&<p>{q.hint}</p>}<div role="status" aria-live="polite">{checked&&<p><strong>{choice?.correct?'That conclusion is supported.':'Revisit the deciding step.'}</strong> {choice?.feedback}</p>}</div>{checked&&!choice?.correct&&repairs[0]&&<p><a href={`/learn/${role}/${repairs[0].week}#section-${repairs[0].section}`}>Review a building block: {repairs[0].title}</a></p>}<ResponseSpace prompt="Explain the deciding fact in your own words. What would you test next?" storageKey={`${week}-practice-${q.id}`}/>{checked&&choice?.correct&&index<questions.length-1&&<button type="button" onClick={()=>{setIndex(index+1);setSelected(null);setChecked(false);setAttempts(0);setHint(false);setHelpUsed(false);}}>Try the changed case</button>}{index===questions.length-1&&checked&&choice?.correct&&<p>Keep your explanation, then attempt the reserved independent case before receiving its teacher feedback.</p>}</section>;
}
