"use client";
import {useEffect,useId,useRef,useState} from "react";
import {ResponseSpace} from "@/components/response-space";
export function PythonLab({week,role,labs}:{week:string;role:string;labs:{title:string;code:string}[]}){
 const id=useId();const[index,setIndex]=useState(0);const[code,setCode]=useState(labs[0]?.code||'');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('Predict the output before running.');const[result,setResult]=useState('');const worker=useRef<Worker|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const box=useRef<HTMLDivElement>(null);
 function end(){if(timer.current)clearTimeout(timer.current);worker.current?.terminate();worker.current=null;setBusy(false);}
 useEffect(()=>{end();setIndex(0);setResult('');},[week,role]);
 useEffect(()=>{try{setCode(localStorage.getItem(`academy-code-v1:${role}:${week}:${index}`)||labs[index]?.code||'');}catch{setCode(labs[index]?.code||'');}setResult('');setStatus('Predict the output before running.');},[week,role,index,labs]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);worker.current?.terminate();},[]);
 function record(text:string){const key=`academy-answer-v1:/learn/${role}/${week}:code:lab-${index}-${Date.now()}`;try{localStorage.setItem(key,text);localStorage.setItem(`academy-answer-meta-v1:${key}`,JSON.stringify({prompt:`Python lab ${index+1}: prediction, code and actual result`,updatedAt:new Date().toISOString()}));}catch{setStatus('Result is shown here. Browser storage is unavailable; print this page to keep it.');}}
 function run(){if(busy)return;setBusy(true);setResult('');setStatus('Loading Python in your browser…');const prediction=box.current?.querySelector('textarea')?.value||'(No prediction recorded)';
  const current=new Worker('/python-lab-worker.mjs',{type:'module'});worker.current=current;
  timer.current=setTimeout(()=>{end();setStatus('Python did not finish loading. Try again or use a paper trace.');},60000);
  current.onerror=()=>{end();setStatus('Python could not load. Try again or use the supplied code as a paper trace.');};
  current.onmessage=({data})=>{
   if(data.type==='ready'){if(timer.current)clearTimeout(timer.current);setStatus('Running Python…');timer.current=setTimeout(()=>{end();const message='Stopped after five seconds. No completed result; check for a loop that never ends.';setStatus(message);record(`Prediction: ${prediction}\n\nCode:\n${code}\n\nExecution: ${message}`);},5000);current.postMessage({type:'run',code});}
   if(data.type==='result'){end();const actual=[data.stdout,data.stderr,data.error].filter(Boolean).join('\n')||'(Program completed without printed output.)';setResult(actual);setStatus(data.error?'Python reported an error. Find the first relevant line, repair it and test again.':'Python completed. Compare the actual output with your prediction.');record(`Prediction: ${prediction}\n\nCode actually run:\n${code}\n\nActual output or error:\n${actual}\n\nExplain any difference and keep a changed test.`);}
  };
 }
 return <section className="classroom-panel python-lab" aria-busy={busy}><h2>Predict, run and debug Python</h2><p>Run a supported example, then change one input and test your explanation. Python runs in this browser. The supplied durations.txt fixture contains fictional values 12 and 8.</p><label htmlFor={`${id}-example`}>Choose a supported example</label><select id={`${id}-example`} value={index} disabled={busy} onChange={e=>setIndex(Number(e.target.value))}>{labs.map((lab,i)=><option key={i} value={i}>{lab.title}</option>)}</select><div ref={box}><ResponseSpace prompt="My predicted output and the deciding step" storageKey={`${week}-lab-${index}-prediction`}/></div><label htmlFor={`${id}-code`}>Python code to run</label><textarea id={`${id}-code`} className="python-editor" spellCheck={false} value={code} rows={10} disabled={busy} onChange={e=>{setCode(e.target.value);setResult('');try{localStorage.setItem(`academy-code-v1:${role}:${week}:${index}`,e.target.value);}catch{}}}/><pre className="print-answer">{code}</pre><div className="learning-actions"><button type="button" disabled={busy||!code.trim()} onClick={run}>Run Python</button><button type="button" disabled={!busy} onClick={()=>{end();setStatus('Stopped by you. No completed result was recorded.');}}>Stop running</button><button type="button" disabled={busy} onClick={()=>{setCode(labs[index].code);setResult('');try{localStorage.removeItem(`academy-code-v1:${role}:${week}:${index}`);}catch{}}}>Restore example</button></div><p role="status" aria-live="polite">{status}</p>{result&&<pre className="code-block actual-python-output" aria-label="Actual Python output or error">{result}</pre>}<ResponseSpace prompt="What changed, why the result follows, and my next test" storageKey={`${week}-lab-${index}-reflection`}/></section>;
}
