import {ArrowDown, CheckCircle2, CircleHelp, GitBranch, Lightbulb, RotateCcw, Search, ShieldCheck, XCircle} from 'lucide-react';
import {topicPlan, type TopicPlan} from '@/lib/topic-plans';
import {ResponseSpace} from '@/components/response-space';

const percentIds=new Set(['ai-3/2','ai-4/27']);
function DotGrid({count,total=count}:{count:number;total?:number}){
 return <div className="topic-dots" aria-hidden="true">{Array.from({length:total},(_,i)=><span key={i} className={i<count?'filled':'empty'}/>)}</div>;
}
function NumericBars({plan}:{plan:TopicPlan}){
 const max=percentIds.has(plan.id)?100:Math.max(1,...plan.items.map(i=>Number(i.value)));
 return <div className="topic-bars"><p className="topic-axis">{percentIds.has(plan.id)?'Percent':'Value'} · shared scale 0–{max}</p>{plan.items.map((item,i)=><div className="topic-bar-row" key={i}><div><strong>{item.label}</strong><span>{item.value}{percentIds.has(plan.id)?'%':''}</span></div><div className="topic-bar-track" aria-hidden="true"><span style={{width:`${100*Number(item.value)/max}%`}}/></div></div>)}</div>;
}
function DiagramBody({plan}:{plan:TopicPlan}){
 const {kind,items}=plan;
 if(kind==='bars')return <NumericBars plan={plan}/>;
 if(kind==='groups')return <div className="topic-group-grid">{items.map((item,i)=><section key={i}><h4>{item.label}</h4><strong className="topic-value">{item.value}</strong><DotGrid count={Number(item.value)}/>{Number(item.value)===0&&<p>No examples in this group.</p>}</section>)}</div>;
 if(kind==='fractions')return <div className="topic-fractions">{items.map((item,i)=>{const [a,b]=item.value.split('/').map(Number);return <section key={i}><h4>{item.label}</h4><div className="topic-fraction-number"><span><b>{a}</b><b>{b}</b></span><strong>= {Number((a/b*100).toFixed(1))}%</strong></div><DotGrid count={a} total={b}/><p>{a} of {b} cases. Filled boxes show the counted portion; outlines complete the denominator.</p></section>;})}</div>;
 if(kind==='pixels')return <div className="topic-pixel-demo"><div className="topic-pixels" aria-label="Two by two pixel grid, row major order">{items.map((i,n)=><div key={n} className={i.value==='1'?'black':'white'}><span>{i.value}</span><small>{i.label}</small></div>)}</div><div><h4>Read rows, then columns</h4><p>0 = white. 1 = black.</p><p>Top row: [0, 1]<br/>Bottom row: [1, 0]</p><p>Change top-left to 1: three squares become black. The values store the picture; recognising what it shows needs another process.</p></div></div>;
 if(kind==='trace')return <div className="topic-table-wrap"><table className="topic-trace"><thead><tr><th scope="col">Step</th><th scope="col">Instruction or field</th><th scope="col">State / result</th></tr></thead><tbody>{items.map((i,n)=><tr key={n}><th scope="row">{n+1}</th><td>{i.label}</td><td><code>{i.value}</code></td></tr>)}</tbody></table></div>;
 if(kind==='matrix'){const positive=plan.id.startsWith('ai-4')?'spotted':'should recommend';return <div className="topic-matrix"><p><strong>Positive = {positive}.</strong> Rows show actual labels; columns show predictions.</p><div className="topic-table-wrap"><table><thead><tr><th scope="col">Actual ↓ / predicted →</th><th scope="col">Positive</th><th scope="col">Negative</th></tr></thead><tbody><tr><th scope="row">Positive</th><td className="correct"><b>{items[0].value}</b>True positive</td><td className="incorrect"><b>{items[1].value}</b>False negative</td></tr><tr><th scope="row">Negative</th><td className="incorrect"><b>{items[2].value}</b>False positive</td><td className="correct"><b>{items[3].value}</b>True negative</td></tr></tbody></table></div><p><strong>Total: {items.reduce((n,i)=>n+Number(i.value),0)}.</strong> Correct: {Number(items[0].value)+Number(items[3].value)}. Errors: {Number(items[1].value)+Number(items[2].value)}.</p></div>;}
 if(kind==='split'){const total=items.reduce((n,i)=>n+Number(i.value),0);return <div className="topic-partitions"><div className="topic-partition-bar" aria-hidden="true">{items.map((i,n)=><div key={n} style={{flex:Number(i.value)}} className={`partition-${n}`}>{i.value}</div>)}</div><div className="topic-partition-legend">{items.map((i,n)=><section key={n}><span className={`partition-swatch partition-${n}`}/><h4>{i.label}</h4><p>{i.value} of {total}</p></section>)}</div></div>;}
 if(kind==='context'){const cap=Number(items[2].value),count=Number(items[0].value)+Number(items[1].value);return <div className="topic-context"><p><strong>Toy limit: {cap} tokens.</strong> Requested: {count}. Overflow: {count-cap}.</p><div className="topic-token-window">{Array.from({length:count},(_,n)=><span key={n} className={n>=cap?'overflow':n<Number(items[0].value)?'prompt-token':'source-token'}><b>{n+1}</b><small>{n>=cap?'Overflow':n<Number(items[0].value)?'Prompt':'Quote'}</small></span>)}</div><p>The last token lies outside this toy window. Select or shorten the input while preserving essential instructions and evidence. Real systems also have output-budget rules.</p></div>;}
 if(kind==='tokens')return <div className="topic-tokenizers">{items.map((i,n)=><section key={n}><h4>{i.label}</h4><div>{i.value.split(' / ').map((token,j)=><code key={j}>{token}</code>)}</div><p>{i.value.split(' / ').length} token{i.value.split(' / ').length===1?'':'s'} in this toy example.</p></section>)}</div>;
 if(kind==='spatial')return <div className="topic-composition" aria-label="Composition plan, not a generated scene"><div className="composition-sky"><strong>{items[0].label}</strong><p>{items[0].value}</p></div><div className="composition-left"><strong>{items[1].label}</strong><p>{items[1].value}</p><small>Larger subject</small></div><div className="composition-right"><strong>{items[2].label}</strong><p>{items[2].value}</p><small>Smaller subject</small></div></div>;
 if(kind==='wave'){const samples=[0,.1,-.1,.3,-.8,1,-.7,.45,-.2,.1,0];return <div className="topic-wave"><p>Schematic samples · same time scale and recording settings · amplitude is relative, not calibrated sound level.</p><svg viewBox="0 0 600 240" role="img" aria-label="Quiet and loud clap signals: the loud signal has three times the illustrated amplitude"><text x="16" y="25">Quiet clap</text><text x="16" y="136">Loud clap</text>{[1,3].map((a,j)=><g key={a}><line x1="145" y1={65+j*105} x2="565" y2={65+j*105} stroke="#94a3b8"/><polyline fill="none" stroke={j?'#0f766e':'#2563eb'} strokeWidth="3" points={samples.map((v,i)=>`${145+i*42},${65+j*105-v*a*15}`).join(' ')}/></g>)}<text x="435" y="235">Time →</text></svg><p>Larger amplitude can support a louder-clap comparison under controlled conditions. It does not reveal word meaning.</p></div>;}
 if(kind==='curve'){const maxX=Math.max(...items.map(i=>Number(i.label)));const points=items.map(i=>[65+Number(i.label)/maxX*460,225-Number(i.value)*1.8]);return <div className="topic-curve"><svg viewBox="0 0 610 295" role="img" aria-label="Validation accuracy: 60 percent at 20 leaves, 70 percent at 40 leaves, 78 percent at 80 leaves"><text x="65" y="18">Validation accuracy (%)</text>{[0,25,50,75,100].map(y=><g key={y}><line x1="65" y1={225-y*1.8} x2="545" y2={225-y*1.8} stroke="#cbd5e1"/><text x="20" y={230-y*1.8}>{y}</text></g>)}<polyline points={points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#0f766e" strokeWidth="3"/>{points.map(([x,y],n)=><g key={n}><circle cx={x} cy={y} r="5" fill="#0f766e"/><text x={x-14} y={y-12}>{items[n].value}%</text><text x={x-10} y="250">{items[n].label}</text></g>)}<text x="200" y="284">Training leaves (count)</text></svg><div className="topic-data-labels">{items.map((i,n)=><span key={n}>{i.label} leaves → {i.value}%</span>)}</div><p>Lines connect the recorded runs; they do not predict unmeasured results. The validation set stays fixed.</p></div>;}
 if(kind==='residual')return <div><NumericBars plan={plan}/><div className="topic-equation">12 cm − 9 cm = <strong>+3 cm</strong></div><p>Actual − predicted is positive here: the prediction is 3 cm too low.</p></div>;
 const sequential=['flow','cycle','checklist'].includes(kind);
 return <><ol className={`topic-cards topic-${kind}`}>{items.map((i,n)=><li key={n}><div className="topic-node-label">{kind==='branch'?<GitBranch aria-hidden="true"/>:kind==='checklist'?<CheckCircle2 aria-hidden="true"/>:<span>{String(n+1).padStart(2,'0')}</span>}<h4>{i.label}</h4></div><p>{i.value}</p>{sequential&&n<items.length-1&&<ArrowDown className="topic-connector" aria-hidden="true"/>}</li>)}</ol>{kind==='cycle'&&<p className="topic-cycle-return"><RotateCcw aria-hidden="true"/> The next round returns to the first stage using the new evidence.</p>}</>;
}

export function TopicDiagram({level,week}:{level:string;week:number}){
 const plan=topicPlan(level,week);
 return <figure className={`topic-diagram topic-kind-${plan.kind}`} data-topic-id={plan.id} data-native-diagram="mechanism" data-diagram-kind={plan.kind}><figcaption><span className="topic-kicker"><Lightbulb aria-hidden="true"/> LOOK • TRACE • EXPLAIN</span><h3>{plan.title}</h3></figcaption><DiagramBody plan={plan}/><div className="topic-reading-note"><Search aria-hidden="true"/><p>{plan.explanation}</p></div></figure>;
}
export function MisconceptionRepair({level,week}:{level:string;week:number}){
 const p=topicPlan(level,week);
 return <section className="topic-repair" data-topic-panel="repair"><h3>Challenge the claim</h3><div className="topic-repair-pair"><div><XCircle aria-hidden="true"/><strong>Claim to question</strong><p>{p.misconception}</p></div><div><ShieldCheck aria-hidden="true"/><strong>Reason from evidence</strong><p>{p.explanation}</p></div></div><p className="topic-discuss"><CircleHelp aria-hidden="true"/>{p.question}</p><ResponseSpace/></section>;
}
export function WorkedCaseStudio({level,week}:{level:string;week:number}){
 const p=topicPlan(level,week);
 return <section className="topic-case" data-topic-panel="worked-case"><div className="topic-case-brief"><span className="topic-kicker">CASE FILE · {level.toUpperCase()} · WEEK {week}</span><h3>Start with the supplied evidence</h3><p>{p.scenario}</p></div><div className="topic-case-question"><CircleHelp aria-hidden="true"/><div><h4>Predict before checking</h4><p>{p.question}</p><ResponseSpace/></div></div><details className="topic-solution"><summary>Compare with the worked explanation</summary><div><p>{p.explanation}</p><h4>Explain the connection</h4><p>Which detail in the situation supports this conclusion? What remains unknown?</p><ResponseSpace/></div></details></section>;
}
export function TopicTeacherPrompt({level,week}:{level:string;week:number}){
 const p=topicPlan(level,week);
 return <div className="topic-teacher-prompt"><h3>Teach this week's distinction</h3><p>{p.teach}</p><h4>Listen for this misconception</h4><p>{p.misconception}</p><h4>Evidence to bring students back to</h4><p>{p.explanation}</p></div>;
}
export function TopicWorkbookPrompt({level,week}:{level:string;week:number}){
 const p=topicPlan(level,week);
 return <section className="topic-workbook-prompt"><span className="topic-kicker">DRAW • TRACE • JUSTIFY</span><h3>{p.title}</h3><p>{p.scenario}</p><strong>{p.question}</strong><div className="topic-workbook-grid">{['Draw or organise the given information','Trace the decision or calculation','Explain your result and its limit'].map(label=><div key={label}><h4>{label}</h4><ResponseSpace/></div>)}</div></section>;
}
