"""Prepare a real classroom pilot; no learner observations or outcomes are invented."""
from pathlib import Path
import json,html,csv
R=Path(__file__).resolve().parents[1];p=json.loads((R/'content/programme.json').read_text());weeks={w['id']:w for w in p['weeks']+p['python_bridge']};tracks=[]
sets=[
('ai-1/1','Foundations: explain a hybrid system',
 {'task':'A classroom door opens when someone approaches. Its label says intelligent entrance. State one observation, one mechanism you cannot determine from that observation, and one record or question that would help distinguish a written rule from a learned model.','answer':'Opening on approach is an observation. The decision mechanism is unknown. Ask for the rule or training record and trace how an input produced the action; an intelligent label does not establish learning.'},
 {'task':'A bus station estimates the number of waiting passengers using a model fitted on labelled camera frames. A written rule displays CALL ANOTHER BUS at estimates of 35 or more. A dispatcher chooses whether to send a bus. The estimate is 40. Identify the three mechanisms, trace the message, and explain why a correctly displayed message does not prove an accurate passenger estimate.','answer':'The estimate is a learned-model prediction; the message follows the written threshold (40 >= 35); dispatch is human action. The threshold can be applied correctly to an inaccurate estimate. Compare the estimate with an appropriately timed, predefined passenger count before judging prediction accuracy.'}),
('python-bridge/5','Python: branch order and boundary tests',
 {'task':'Trace the code for reading=20, then reading=19 and reading=101. Explain why validity is checked before the lamp rule.','code':'reading = 20\nif not 0 <= reading <= 100:\n    action = "invalid"\nelif reading < 20:\n    action = "on"\nelse:\n    action = "off"\nprint(action)\n','answer':'20 gives off, 19 gives on, 101 gives invalid. Validity is checked first so invalid inputs cannot be treated as valid lamp decisions.'},
 {'task':'Write or trace a branch chain: valid readings are 0 through 100 inclusive. Invalid readings produce invalid; valid readings below 25 produce on; all other valid readings produce off. Predict 24,25,100,101 and -1, then justify the order and boundaries.','code':'reading = 25\nif not 0 <= reading <= 100:\n    action = "invalid"\nelif reading < 25:\n    action = "on"\nelse:\n    action = "off"\nprint(action)\n','answer':'24 on; 25 off; 100 off; 101 invalid; -1 invalid. Check validity before the threshold, include both valid endpoints, and use a strict less-than comparison for on.'}),
('ai-4/10','Machine Learning: fit and compare a baseline',
 {'task':'Training labels are A,A,B. Validation labels are A,B,B. Fit a training-majority baseline and list its three predictions. A candidate predicts A,B,A. Score both on these validation rows, state the difference in correct examples and percentage points, and name an unsupported claim.','answer':'Fit A from the training majority. Predict A,A,A. Baseline gets row 1: 1/3. Candidate gets rows 1 and 2: 2/3. It gains one correct example and about 33.3 percentage points. This tiny comparison does not establish performance on future cases.'},
 {'task':'Training labels are blue,red,blue,blue,red. Validation labels are blue,red,red,blue,blue. Fit the training-majority baseline and list its five predictions. A candidate predicts red,red,blue,red,blue. Score both, state the difference in correct examples and percentage points, and explain the limit of this comparison.','answer':'Training has three blue and two red, so predict blue five times. Baseline matches rows 1,4,5: 3/5 or 60%. Candidate matches rows 2,5: 2/5 or 40%. It loses one correct example and is 20 percentage points lower. The small validation set does not establish future performance or suitability for deployment.'})]
for week,title,baseline,delayed in sets:
 w=weeks[week];post={k:v for k,v in w['method']['independent'].items() if k in ['task','answer','code']}
 tracks.append({'id':week,'title':title,'goal':w['method']['goal'],'baseline':baseline,'post':post,'delayed':delayed,'sessions':w['method']['sessions'],'exposure_note':'Ask whether learners have seen any selected case before. Mark prior exposure; use a genuinely different teacher-checked case when a selected task is familiar.'})
if (R/'lib').exists():(R/'lib/pilot-data.json').write_text(json.dumps(tracks,ensure_ascii=False,indent=2))
(R/'content/pilot-teacher-data.json').write_text(json.dumps(tracks,ensure_ascii=False,indent=2))
fields=['track','group','learnerCode','phase','date','priorExposure','supportUsed','explanation','trace','limits','minutes','learnerEvidence','confusingPart','accessBarrier','nextAction']
with (R/'teacher/classroom-pilot-template.csv').open('w',newline='') as f:csv.writer(f).writerow(fields)
e=html.escape
body='<main><header class="hero"><h1>Run a classroom pilot</h1><p>Prepare, observe, review and revise. No real learner results have been recorded by this package.</p></header><p><a href="index.html">Teacher programme</a> · <a href="classroom-pilot-template.csv">Blank observation CSV</a></p><section class="chapter"><h2>Choose and schedule</h2><p>Choose the track that matches actual readiness. Record the class or anonymous group code, approximate group size and actual dates. The three tracks sample different readiness stages; learners do not need to complete all three.</p><ol><li>Before teaching, check prior exposure and collect the baseline without hints.</li><li>Teach the complete selected lesson, using its staged plan and support where needed. Record time and barriers rather than forcing a fixed pace.</li><li>Collect the post-lesson independent case before feedback. Record any help separately.</li><li>Return after a teaching delay, such as one week when appropriate; use the held-back changed task before reviewing old answers.</li><li>Compare only learners with matching baseline and later records. Review explanations, traces and limits; do not treat a quiz selection or progress tick as mastery.</li><li>Repair confusing wording, pictures, examples or timing, and repeat on a fresh case. Preserve the actual evidence and revision.</li></ol><p>The tasks differ, so observations are descriptive. This small pilot cannot establish that the lesson caused a learning gain. A real teacher and learners must carry out the sessions.</p></section>'
for track in tracks:
 body+='<section class="chapter"><h2>'+e(track['title'])+'</h2><p>'+e(track['goal'])+'</p><p>'+e(track['exposure_note'])+'</p>'
 for phase in ['baseline','post','delayed']:
  case=track[phase];body+='<h3>'+phase.title()+' task — hold back until the relevant session</h3><p>'+e(case['task'])+'</p>'
  if case.get('code'):body+='<pre class="code"><code>'+e(case['code'])+'</code></pre>'
  handout_name=track['id'].replace('/','-')+'-'+phase+'.html'
  folder=R/'teacher/pilot';folder.mkdir(exist_ok=True)
  handout='<main><header class="hero"><h1>'+e(track['title'])+'</h1><p>'+phase.title()+' independent task</p></header><section class="chapter"><h2>Explain your reasoning before feedback</h2><p>'+e(case['task'])+'</p>'+('<pre class="code"><code>'+e(case['code'])+'</code></pre>' if case.get('code') else '')+'<h3>My deciding step, trace and limitation</h3><p>________________________________________________________________</p><p>________________________________________________________________</p><p>________________________________________________________________</p><p>Support used: none / hint / model. Actual minutes: ________</p></section></main>'
  (folder/handout_name).write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(track['title'])+' '+phase+' task</title><link rel="stylesheet" href="../../assets/programme.css"></head><body>'+handout+'</body></html>')
  body+='<p><a href="pilot/'+handout_name+'">Print the selected learner handout (without answers)</a></p>'
  body+='<details><summary>Teacher reasoning key</summary><p>'+e(case['answer'])+'</p></details>'
 body+='</section>'
body+='<section class="chapter"><h2>Judge the recorded evidence</h2><p>For explanation, trace/test and limits, record not yet, with support or independent. Keep a learner quote, written response or described demonstration. Record support used, actual minutes, confusing language, access barriers and the next teaching action.</p><p>Use anonymous learner codes. The hosted teacher pilot studio stores records in the current browser and exports CSV/JSON. Keep a downloaded record before clearing a shared device. Student accounts cannot open the studio or teacher reasoning keys.</p></section></main>'
(R/'teacher/PILOT_GUIDE.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Teacher classroom pilot</title><link rel="stylesheet" href="../assets/programme.css"></head><body>'+body+'</body></html>')
print('Prepared three teacher pilot tracks, fresh delayed cases and a blank observation template; no learner results.')
