"""Add an evidence-informed teaching cycle without removing any curriculum content."""
from pathlib import Path
from copy import deepcopy
import json
ROOT=Path(__file__).resolve().parents[1]
def p(text):return {'type':'paragraph','text':text}
def h(text):return {'type':'subheading','text':text}
def response(label,lines=4):return {'type':'response','label':label,'lines':lines}
def table(headers,rows):return {'type':'table','rows':[headers]+rows}
def tag(blocks,role,kind):
 return [dict(deepcopy(b),teaching_method={'role':role,'kind':kind}) for b in blocks]
def first_paragraph(section):return next((b['text'] for b in section['blocks'] if b['type']=='paragraph'),'')
# Parallel readiness tasks use changed inputs and include boundaries or missing data.
BRIDGE_CASES=[
 ('Trace variables and a change','packs = 3\nper_pack = 7\ntotal = packs * per_pack\nprint(total)\n','21\n','Predict the printed value. Change only packs to 5 and predict again. Explain which statements apply a written rule.', '21, then 35. The multiplication rule is written; changing an input is not fitting an AI model.'),
 ('Keep division meanings separate','total = 17\ngroups = 4\nprint(total / groups, total // groups, total % groups)\n','4.25 4 1\n','Predict all three outputs and explain their different meanings. Repeat the trace for total=0, keeping groups=4.', '4.25, 4 and 1 are ordinary division, whole-number quotient and remainder. At total=0: 0.0, 0 and 0. Groups remains nonzero.'),
 ('Trace a string precisely','place = "North"\nprint(place.lower())\nprint(len(place))\nprint(place[1:4])\n','north\n5\nort\n','Predict each output. Explain the start and stopping positions of the slice. What would place[0:0] contain?', 'north, 5 and ort. The slice includes indices 1,2,3 but excludes 4. The slice [0:0] is empty, not the first character.'),
 ('Separate a boundary from validity','reading = 29\nprint(reading < 30, 0 <= reading <= 100)\n','True True\n','Predict both booleans for readings 29, 30 and -1. Why is the first condition alone insufficient to validate a reading?', '29: True True; 30: False True; -1: True False. The threshold can be true for an invalid input, so validity needs its own condition.'),
 ('Trace branch order','reading = 30\nif not 0 <= reading <= 100:\n    action = "invalid"\nelif reading < 30:\n    action = "on"\nelse:\n    action = "off"\nprint(action)\n','off\n','Predict the action for 30, then trace 29 and -1. Explain why validity is checked before the lamp decision.', '30 gives off, 29 gives on, -1 gives invalid. Checking validity first prevents an invalid negative reading from being accepted as a lamp-on decision.'),
 ('Count iterations and a stopping point','total = 0\nfor value in range(2, 6):\n    total = total + value\nprint(total)\n','14\n','List every value visited and each running total. Then predict the result for range(2,2).', 'Values 2,3,4,5 give totals 2,5,9,14. Range(2,2) is empty, so total remains 0. The upper endpoint is excluded.'),
 ('Distinguish a value from an index','values = [4, 9, 2]\nprint(values[1])\nprint(values[-1])\nprint(len(values))\n','9\n2\n3\n','Predict the three outputs. If the second print uses values[3] instead, where does execution stop and which later output is not produced?', 'Outputs are 9,2,3. With values[3], the first print produces 9, then IndexError occurs; the final length print is not reached. Positive valid indices are 0,1,2.'),
 ('Keep zero and missing separate','record = {"count": 0, "kind": "book"}\nprint(record.get("count"))\nprint(record.get("price"))\nprint("price" in record)\n','0\nNone\nFalse\n','Predict every output. Explain why a stored count of zero and a missing price are different facts.', '0 is a supplied count. None here is the default for the missing price key; False confirms the key is absent. Do not invent a zero price from missing evidence.'),
 ('Follow arguments and returns','def bundle(n, each):\n    total = n * each\n    return total\nfirst = bundle(3, 4)\nsecond = bundle(2, 5)\nprint(first, second)\n','12 10\n','Trace both calls, their local totals and returned values. What would bundle(0,5) return?', 'Local totals and returns are 12 and 10; printed values are 12 10. Bundle(0,5) returns 0. The local variable does not become a global name.'),
 ('Connect two functions','def in_range(x):\n    return 0 <= x <= 10\ndef badge(x):\n    if not in_range(x):\n        return "invalid"\n    if x < 5:\n        return "low"\n    return "high"\nprint(badge(4), badge(5), badge(11))\n','low high invalid\n','Trace the calls for 4,5,11. Then predict badge(0) and badge(10), identifying the comparisons that decide them.', 'Printed labels are low high invalid. Badge(0) is low and badge(10) high; both boundaries are valid. The validity function is used before choosing a category.'),
 ('Explain what tests establish','def below_limit(x):\n    return x < 10\nassert below_limit(9) is True\nassert below_limit(10) is False\nassert below_limit(11) is False\nprint("three checks passed")\n','three checks passed\n','Predict the output. If the function uses x <= 10, identify the first failing assertion. Do these three checks prove all input types are safe?', 'The original prints three checks passed. With <=, the assertion for 10 fails first and the final print is not reached. Three tested numbers do not establish every value or input type is handled.'),
 ('Report coverage with the result','rows = [{"score": 2}, {"score": 6}, {}]\nvalues = []\nfor row in rows:\n    value = row.get("score")\n    if value is not None:\n        values.append(value)\nif len(values) > 0:\n    mean = sum(values) / len(values)\nelse:\n    mean = None\nprint(len(values), len(rows), mean)\n','2 3 4.0\n','Trace the supplied missing-value policy and predict the output. State the mean denominator and coverage. What should be reported if every row is missing its score?', 'Output 2 3 4.0: mean 4 over two supplied scores, coverage 2/3, one unmeasured score. With three empty rows, output is 0 3 None; no observed mean exists. Missing records are not zero scores.')]

# Readiness follows the actual twelve lesson topics, including argument order and returns.
BRIDGE_CASES[1]=('Trace values, types and reassignment','count = 4\nnote = "4"\nestimate = count / 2\nfits = count <= 5\ncount = count + 3\nprint(count, note, estimate, fits)\nprint(type(count).__name__, type(note).__name__, type(estimate).__name__, type(fits).__name__)\n','7 4 2.0 True\nint str float bool\n','Predict both output lines and explain why estimate stays unchanged when count is reassigned. Repeat the trace with initial count=0. Explain why note is text even though its printed characters look like a number.','Original outputs: 7 4 2.0 True, then int str float bool. Estimate was calculated as 2.0 before reassignment; it is not a live formula. With initial count=0: 3 4 0.0 True, with the same types. Note is the quoted string "4", independent of the integer count.')
BRIDGE_CASES[2]=('Group an expression deliberately','print((17 + 5) // 5)\nprint(17 + 5 // 5)\nprint(17 / 5, 17 // 5, 17 % 5)\n','4\n18\n3.4 3 2\n','Predict each line. Explain which calculation groups addition before division. What would (17+5)%5 return, and how do /, // and % differ for the supplied positive integers?','The first line is4 because22//5=4. The second is18 because5//5 is evaluated before adding17. The final line is3.4 3 2: ordinary division, whole quotient and remainder for17 divided by5. (17+5)%5 is2. Parentheses choose the grouped calculation; they are not optional when that meaning is intended.')
BRIDGE_CASES[3]=('Combine requirements without replacing AND','pages = 90\ngenre = "science"\navailable = False\nprint(genre == "science" and pages <= 100)\nprint((genre == "science" and pages <= 100) and available)\nprint(not available)\nprint(genre == "science" or pages <= 100)\n','True\nFalse\nTrue\nTrue\n','Predict all four booleans. Eligibility requires science AND at most100 pages AND availability. Repeat with genre="history" and all other values unchanged. Which OR result could wrongly suggest the genre requirement passed?','Original results: True, False, True, True. Full eligibility is False because availability is False. With history: False, False, True, True. The final OR remains True because90<=100; it does not establish that the science requirement passed. NOT available is True in both traces.')
BRIDGE_CASES[7]=('Match positional arguments to parameters','def difference(first, second):\n    return first - second\nprint(difference(11, 4))\nprint(difference(4, 11))\n','7\n-7\n','Predict both returned and printed values, showing which argument supplies first and second. What is displayed if the program contains only the function definition and no calls? Why does swapping these arguments change the result?','The first call returns and prints7; the second returns and prints−7. Positional arguments fill first then second, and subtraction is ordered. A definition alone displays nothing and does not execute its body. The same function uses the supplied values for each call.')
BRIDGE_CASES[8]=('Use returns and keep local state local','def twice(n):\n    total = 2 * n\n    return total\nfirst = twice(3)\nsecond = twice(5)\nprint(first, second, first + second)\n','6 10 16\n','Trace both calls and the final expression. If return total is removed from the function, does this final print complete? Would a separate print(total) outside the function have access to its local variable?','With the return: first=6, second=10, sum16, so output is6 10 16. Removing the return makes both calls return None; evaluating first+second raises TypeError before print runs, so no line is printed. In this shown program total is local, so an outside print(total) raises NameError. Each call has its own local computation.')
BRIDGE_CASES[9]=('Read, update and pass a dictionary record','def describe(record):\n    count = record.get("count")\n    if count is None:\n        return "missing"\n    return count\nrecord = {"count": 0}\nprint(describe(record))\nrecord["count"] = 3\nprint(describe(record))\nprint(describe({}))\n','0\n3\nmissing\n','Predict the three outputs and trace the named-field update. Explain why zero and a missing count produce different results. If the condition becomes if not count, which supplied record is first handled incorrectly?','Outputs are0,3,missing. A stored0 is a supplied value; an absent field returns None under get here. The update replaces count with3 before the second call. Using if not count would incorrectly return missing for the original count0 because zero is false in a Boolean test; testing None keeps absence separate.')
BRIDGE_CASES[10]=('Preserve records and report measured coverage','rows = [{"score": 2}, {"score": 6}, {}]\nvalues = []\nfor row in rows:\n    value = row.get("score")\n    if value is not None:\n        values.append(value)\nobserved_total = sum(values)\nif len(values) > 0:\n    mean = observed_total / len(values)\nelse:\n    mean = None\nprint(observed_total, len(values), len(rows), mean)\n','8 2 3 4.0\n','Trace the named fields and missing-value policy. Predict the output, state the observed total and mean denominator, and report coverage. What changes if all three rows are empty records?','Output8 2 3 4.0: observed total8, two supplied scores out of three records, mean4 over denominator2. With three empty records, output0 0 3 None: the empty observed sum is0 by the supplied summing procedure, coverage0/3, and no observed mean exists. It does not claim the missing scores were zero or that the true total is known.')
BRIDGE_CASES[11]=('Use boundary tests to reveal a function defect','def below_limit(x):\n    return x < 10\nassert below_limit(9) is True\nassert below_limit(10) is False\nassert below_limit(11) is False\nprint("three checks passed")\n','three checks passed\n','Predict the output. If the function mistakenly uses x<=10, identify the first failing assertion and whether the final print happens. State the repair and which earlier tests must be rerun. Do these cases prove all input types are handled?','The supplied function prints three checks passed. With <=10, the assertion for10 fails first and the final print does not run. Repair the comparison to<10 and rerun all three cases to check the fix and preserve neighbouring results. These numerical boundary tests do not establish every value or input type is safe.')

SESSION_ROWS=[
 ['Session 1 · Understand · 45 min','0–7: recall and prerequisite; 7–15: inspect the concrete case and predict; 15–30: teacher models the worked trace; 30–40: learners explain a step using the text and visual; 40–45: check the core idea.','Sections 1–6; record the brief recall in the workbook.'],
 ['Session 2 · Practise · 45 min','0–5: retrieve the procedure; 5–15: W2 completion practice; 15–23: explain and check with a partner; 23–30: each learner answers the misconception check; 30–40: targeted reteaching or a harder variation; 40–45: prepare the investigation.','Sections 7–10; use the matching workbook W2 and misconception check.'],
 ['Session 3 · Investigate and transfer · 45 min','0–5: retrieve the decision rule; 5–20: investigate or trace; 20–30: start the independent case; 30–38: connect the project; 38–43: act on feedback; 43–45: plan the return check.','Sections 9 and 11–14. Give extra time to finish the full task set; use Section 15 when the week includes a coding lab.']]

def find_independent(w,c,seen):
 if w['id'].startswith('python-bridge/'):
  title,code,stdout,task,answer=BRIDGE_CASES[w['week']-1]
  return {'title':title,'task':task,'code':code,'expected_stdout':stdout,'answer':answer,'source':'new parallel Python readiness case'}
 source=w['sources']['rebuilt']
 if source in seen:
  from parallel_assessments import CASES
  if w['id'].replace('ai-','ai') not in CASES:raise ValueError('Fresh case needed: '+w['id']+' source '+source)
  task,answer=CASES[w['id'].replace('ai-','ai')]
  return {'title':'Changed independent case','task':task,'answer':answer,'source':'new parallel transfer case'}
 q=c['workbook'][3]
 return {'title':q['title'],'task':q['prompt'],'answer':q['answer'],'source':'primary source W4, first curriculum occurrence'}

def apply_method(programme,sources):
 allweeks=programme['weeks']+programme['python_bridge'];lookup={w['id']:w for w in allweeks}
 contexts={w['id']:sources['rebuilt'][w['sources']['rebuilt']] for w in allweeks}
 exposure={}
 for w in allweeks:
  for source in [w['sources']['rebuilt']]+w['sources'].get('additional',[]):exposure.setdefault(source,[]).append(w['id'])
 coverage=[];seen=set()
 for collection in [programme['weeks'],programme['python_bridge']]:
  for position,w in enumerate(collection):
   c=contexts[w['id']];practice=c['workbook'][1];claim,repair=c['teacher']['misconceptions'][0]
   previous=[collection[position-offset] for offset in [1,3,6] if position>=offset and collection[position-offset]['level']==w['level']]
   if not previous and not w['id'].startswith('python') and w['level']>1:
    previous=[next(x for x in programme['weeks'] if x['level']==w['level']-1 and x['week']==36)]
   review=[]
   for old in previous:
    oldc=contexts[old['id']]
    review.append({'week':old['id'],'title':old['title'],'prompt':'Without opening the old lesson, explain one key idea from '+old['title']+'. Give an example and a mistake that the idea helps you avoid.','expected':oldc['workbook'][0]['answer'],'goal':oldc['goals'][0]})
   independent=find_independent(w,c,seen)
   seen.update([w['sources']['rebuilt']]+w['sources'].get('additional',[]))
   w['earlier_independent_answer']=w['independent_answer'];w['independent_answer']=independent['answer']
   hinge='Use the worked case for '+c['title']+'. Proposed explanation: “'+claim+'”. Decide whether this explanation is supported. Point to the step or supplied fact that decides; explain your repair if needed.'
   future=[x['id'] for x in collection[position+1:] if x['level']==w['level'] and x['week']-w['week'] in [1,3,6]]
   repeated=exposure[w['sources']['rebuilt']]
   method={'version':'1.0','goal':c['goals'][0],'goals':c['goals'],'sessions':SESSION_ROWS,'retrieval':review,'review_at':future,'practice':practice,'hinge':{'prompt':hinge,'answer':repair},'independent':independent,'case_exposure':repeated,'connected_topics':[]}
   w['method']=method
   student_start=[h('Your learning target')]+[p('I can '+g[0].lower()+g[1:].rstrip('.')+'.') for g in c['goals']]
   student_start += [h('Remember before reading'),p('Close your notes first. A rough first answer helps us choose the right starting point; it is not a score for your ability.')]
   student_start += [p(q['prompt']) for q in review] if review else [p(c['prerequisite']['prompt'])]
   student_start += [p('After trying, check the relevant lesson or ask your teacher. Change the part of your explanation that the evidence shows was wrong.')]
   w['sections'][0]['blocks']=tag(student_start,'student','retrieval-and-goal')+w['sections'][0]['blocks']
   w['sections'][2]['blocks'] += tag([h('Connect the picture and the explanation'),p('Point to the input, the deciding step and the result in this week’s visual. Explain the same step in ordinary words. A picture helps when you can say what each part represents.')],'student','visual-explanation')
   w['sections'][5]['blocks'] += tag([h('Learn from the worked case'),p('Cover the result before checking it. Say what is given, choose the procedure, and follow one step at a time. Then uncover the result and explain your first mismatch. Ask why a step is allowed, not only what number it produces.')],'student','model-and-explain')
   w['sections'][7]['blocks'] += tag([h('Practise with less help: '+practice['title']),p('Use workbook W2 for the connected example “'+c['title']+'”. First fill the input and rule boxes. Try the middle steps before asking for a hint. After a hint, try the next step yourself.'),table(['Plan','Do','Check'],[['What is given? Which rule or procedure applies?','Record each intermediate step.','Does the result follow? What remains unknown?']]),p('Explain your trace to a partner. Your partner points to one step to check. Swap roles on the next case. Each person writes their own explanation.'),h('Check your reasoning'),p(hinge),p('Answer on your own before discussion. If you are unsure, say which step you need help with.')],'student','fading-and-hinge')
   w['sections'][8]['blocks'] += tag([h('Plan → try → check'),p('Before trying: what do I expect, and why? While trying: which step could first go wrong? Afterwards: what did I actually observe, and what should change? Keep “not run” if you only traced the procedure.')],'student','self-regulation')
   fresh=[h('Independent case: '+independent['title']),p(independent['task'])]
   if independent.get('code'):fresh.append({'type':'code','text':independent['code']})
   fresh += [response('My independent explanation, trace and limits',7),p('Attempt this case before feedback. Record any help. Earlier examples below are further practice; a case already practised with feedback cannot establish fresh transfer.')]
   w['sections'][13]['blocks']=tag(fresh,'student','independent-transfer')+w['sections'][13]['blocks']
   w['sections'][13]['blocks'] += tag([h('Use feedback to improve'),p('Attempt the independent case before hints. Record whether you worked alone, used a hint or followed a model. After feedback, fix the first unsupported step and explain why it changed. A later check uses a changed case, not a copied answer.')],'student','transfer-and-feedback')
   wb_recall=[p('Try the recall before opening notes. Then use a different colour or a labelled second line to correct your explanation.')]
   wb_recall += sum(([h(q['title']),p(q['prompt']),response('My remembered idea, example and correction',3)] for q in review),[]) if review else [p(c['prerequisite']['prompt']),response('My starting explanation',3)]
   wb_sections=[{'title':'Recall and choose your starting point','blocks':tag(wb_recall,'workbook','retrieval')},{'title':'Practise with fading help','blocks':tag([p('Use W2: '+practice['title']+' for '+c['title']+'. Record the answer once; the lesson and workbook refer to the same attempt.'),table(['Given inputs','Procedure I chose','Middle steps','Result and check'],[['','','','']]),response('The step I completed without help, and the hint I needed',3)],'workbook','fading')},{'title':'Individual reasoning check','blocks':tag([p(hinge),response('My explanation before partner discussion',4)],'workbook','hinge')}]
   wb_sections.append({'title':'Independent transfer case','blocks':tag(fresh,'workbook','independent-transfer')})
   w['workbook']=wb_sections+w['workbook']+[{'title':'Feedback, return check and learning record','blocks':tag([table(['Evidence','My record'],[['Worked alone / hint / model',''],['First step I repaired and why',''],['New case checked later; date and result',''],['What I can now explain without notes',''],['One remaining question','']]),p('Revisit this idea with your teacher after a delay. Familiarity is different from explaining and using it on a changed case.')],'workbook','feedback-record')}]
   prep=[h('Teach the learning cycle'),p('Primary target: '+c['goals'][0]),table(['Session','Sequence and minutes','Resources'],SESSION_ROWS),p('This is a starting allocation of 135 minutes, not a validated duration. Preserve all named topics. Schedule extra time for connected examples, the full investigation, independent cases and project building. Repeated copies of a case share one recorded attempt; they are not new evidence.')]
   if len(repeated)>1:prep += [p('Case exposure check: this source example appears in '+', '.join(repeated)+'. Reuse a familiar case for recall or modelling; verify that the case used to assess transfer has not already received feedback.')]
   prep += [h('Retrieval answer guidance')]
   for q in review:prep += [h(q['title']),p(q['prompt']),p('Look for: '+q['goal']),p('Reference example, not the only acceptable wording: '+q['expected'])]
   if not review:prep += [p(c['prerequisite']['prompt']),p(c['prerequisite']['answer'])]
   w['teacher'][0]['blocks']=tag(prep,'teacher','planning-and-retrieval')+w['teacher'][0]['blocks']
   model=[h('Model the reasoning aloud'),p('Use the complete worked example below before asking learners to complete W2. Reveal a small part, invite a prediction, then explain the deciding step. These teacher notes contain solutions; do not reveal the independent case answer during modelling.')]+[deepcopy(b) for b in c['lesson'][2]['blocks']]
   model += [table(['Thinking move','Teacher prompt'],[['Plan','What is given? What is the question? Which procedure fits these facts?'],['Do','Point to each input and intermediate step in the worked trace. Name the rule that allows the next step.'],['Check','Does the output answer the question? Which assumption or limitation prevents a larger claim?']]),p('Use the diagram and verbal explanation together. Ask learners to match a sentence to a specific visual step; do not assign learners fixed visual or auditory learning styles.')]
   w['teacher'][1]['blocks'] += tag(model,'teacher','think-aloud')
   w['teacher'][2]['blocks'] += tag([h('Reduce help deliberately'),p('Completion task: '+practice['prompt']),p('Teacher check: '+practice['answer']),p('Start by identifying the given inputs together. Leave the intermediate steps blank. If needed, model one step, then withdraw that help on the next step. Move to a full trace only when the partial trace is understood. For partners, alternate explainer and checker; collect a response from every learner before discussion.'),h('Individual reasoning check'),p(hinge),p('Expected correction: '+repair),p('Collect explanations, not only yes/no votes. If a misunderstanding is common, re-model the relevant step for the class. If it affects a few learners, give a short targeted group explanation while others solve a more demanding variation.')],'teacher','fading-and-hinge')
   w['teacher'][3]['blocks'] += tag([h('Match the support to the first error'),table(['What the response shows','Next teaching action'],[['Missing or misread facts','Read the case aloud, mark supplied versus unknown facts, and let the learner restate it.'],['Wrong procedure','Return to the deciding step in the worked case. Contrast it with the proposed incorrect explanation.'],['Arithmetic or implementation error','Trace intermediate values or lines; preserve the first mismatch and retry that step.'],['Correct result without a reason','Ask for a trace and a changed case before marking independent understanding.'],['An unsupported wider claim','Ask which supplied evidence supports the claim and which further observation would be needed.']]),p('Offer an oral explanation, drawing, enlarged visual or fewer examples when that removes a reading/writing barrier. Keep the same reasoning goal. Stretch secure learners by changing a boundary or assumption and asking them to defend the effect, not simply by assigning more of the same questions.')],'teacher','responsive-support')
   assess=[h('Assess independent transfer'),p('Selected case: '+independent['task'])]
   if independent.get('code'):assess.append({'type':'code','text':independent['code']})
   assess += [h('Selected case answer'),p(independent['answer']),table(['Dimension','Evidence required'],[['Explanation','Names the applicable idea or procedure and ties it to the supplied facts.'],['Trace and result','Preserves the given inputs and shows the relevant intermediate steps; distinguishes a prediction from an observed execution.'],['Limits','States the assumptions, missing evidence or conditions under which the result would change.']]),p('Record each dimension as not yet, with support, or independent. Accept a valid alternative procedure with a defensible trace. Do not penalise an honestly recorded model failure if the learner correctly explains its evidence and limits.'),h('Feedback that the learner uses'),p('Name the earliest unsupported step and give one action to repair it. Have the learner make that repair now and explain why. Then assess the relevant skill on a fresh, fully specified case. Confirm it was not previously practised with feedback; solve and check the new case before assigning it. A follow-up design prompt is a starting brief, not automatically an equivalent test.')]
   w['teacher'][4]['blocks'] += tag(assess,'teacher','assessment-and-feedback')
   w['teacher'][5]['blocks'] += tag([h('Plan the delayed return'),p('Suggested return points in this level: '+(', '.join(future) if future else 'plan a review after the level ends')+'. Use actual classroom dates, adjusting for holidays and gaps. One, three and six teaching weeks are scheduling choices, not a claimed optimal spacing.'),p('At a delayed check, ask for the idea from memory and a changed application. Compare with the earlier independent response and record support used. For a new level, revisit the previous capstone before checking the new prerequisites.'),table(['Record','Teacher evidence'],[['Learner code and date',''],['Concept and case used; prior exposure',''],['Explanation / trace / limits',''],['Support and first repair',''],['Changed case and delayed outcome',''],['Next teaching action','']]),p('Use the evidence to choose reteaching or the next step. A completed page, confidence rating or attractive project does not by itself demonstrate understanding.')],'teacher','delayed-review')
   for source in w['sources'].get('additional',[]):
    connected=sources['rebuilt'][source];q=connected['workbook'][1];mis,correct=connected['teacher']['misconceptions'][0]
    check='For '+connected['title']+', use its worked case to evaluate this proposed explanation: “'+mis+'”. Explain the deciding step.'
    method['connected_topics'].append({'source':source,'title':connected['title'],'goal':connected['goals'][0],'practice':q['prompt'],'hinge':check,'answer':correct})
    w['sections'][7]['blocks'] += tag([h('Practise the connected topic: '+connected['title']),p('Use its named workbook W2. Identify the given inputs, try the middle steps with less help, then explain your trace. Check this claim before group discussion: '+mis)],'student','connected-cycle')
    w['teacher'][2]['blocks'] += tag([h('Connected teaching cycle: '+connected['title']),p('Target: '+connected['goals'][0]),p('Reserve further sessions for this topic; the 135-minute primary plan does not absorb all added content.'),p('Completion practice: '+q['prompt']),p('Teacher check: '+q['answer']),p('Individual check: '+check),p('Expected correction: '+correct),p('Apply the same support, independent transfer and delayed-review decisions to the named connected-topic workbook tasks.')],'teacher','connected-cycle')
   coverage.append({'week':w['id'],'retrieval_from':[q['week'] for q in review],'review_at':future,'primary_case':c['title'],'hinge':hinge,'independent_source':independent['source'],'connected_topics':[x['title'] for x in method['connected_topics']]})
 programme['teaching_method']={'version':'1.0','cycle':['Recall','Model aloud','Practise with fading help','Check individual reasoning','Investigate','Transfer independently','Act on feedback','Revisit after a delay'],'evidence_sources':['https://ies.ed.gov/ncee/wwc/practiceguide/1','https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/metacognition','https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/feedback'],'status':'Evidence-informed design; classroom impact and pacing not yet established.'}
 programme['pacing']='Begin with three 45-minute sessions for the primary weekly cycle. Reserve further sessions for connected topics, complete investigations and projects; adjust using learner evidence.'
 (ROOT/'reports/teaching-method-coverage.json').write_text(json.dumps(coverage,indent=2))
 return programme
